### ISSUE TITLE
Cant create a new controller

### ISSUE THREAD

**Issue by nunomaduro** [Zamerick/foundry#1]
While trying to create a new controller I got this issue.

```foundry make:controller UserController```

```
In Filesystem.php line 41:
                                                                               
  File does not exist at path /home/nunomaduro/Work/foundry/app/Templates/con  
  troller.plain.stub  
```

**Comment by Zamerick** [comment]
Hey, thanks for trying out foundry. I'll look into this issue tonight.

**Comment by Zamerick** [comment]
This and a few other commands had their associated stubs reorganized into sub folders, but the associated getStub() calls had not been altered to account for this. I just pushed a new version that should take care of this.

Have a great day!
